DROP TABLE IF EXISTS TASK_QUEUE;

CREATE TABLE TASK_QUEUE(
TASK_ID INTEGER,
INSTANCE_ID INTEGER, 
SERVER_COMMAND TEXT, 
SERVER_COMMAND_ARGS TEXT, 
TASK_STATUS TEXT, 
INSERT_TIME DATE DEFAULT CURRENT_DATE, 
START_TIME DATE, 
END_TIME DATE, 
TASK_OUTPUT TEXT,
WORKING_DIR TEXT,
PRIMARY KEY(TASK_ID)
);

INSERT INTO TASK_QUEUE 
(TASK_ID, INSTANCE_ID, SERVER_COMMAND, SERVER_COMMAND_ARGS) 
VALUES 
(1,1,'ls', null)