DELETE FROM TASK_QUEUE WHERE 1=1;

INSERT INTO TASK_QUEUE (ID, SCHEDULE_ID, STATUS, SERVER_COMMAND)
VALUES (1,1,'PENDING', './testScript1.sh');

INSERT INTO TASK_QUEUE (ID, SCHEDULE_ID, STATUS, SERVER_COMMAND)
VALUES (2,1,'PENDING', './testScript2.sh')